# Login details
USERNAME = 'username'
PASSWORD = 'password'

# Word count details
SAVE_DIR = 'word_counts'
COMMENTS_PER_SUBREDDIT = 1000
SUBREDDITS = [
    'announcements',
    'Art',
    'AskReddit',
    'askscience',
    'aww',
    'blog',
    'books',
    'creepy',
    'dataisbeautiful',
    'DIY',
    'Documentaries',
    'EarthPorn',
    'explainlikeimfive',
    'Fitness',
    'food',
    'funny',
    'Futurology',
    'gadgets',
    'gaming',
    'GetMotivated',
    'gifs',
    'history',
    'IAmA',
    'InternetIsBeautiful',
    'Jokes',
    'LifeProTips',
    'listentothis',
    'mildlyinteresting',
    'movies',
    'Music',
    'news',
    'nosleep',
    'nottheonion',
    'oldschoolcool',
    'personalfinance',
    'philosophy',
    'photoshopbattles',
    'pics',
    'science',
    'Showerthoughts',
    'space',
    'sports',
    'television',
    'tifu',
    'todayilearned',
    'TwoXChromosomes',
    'UpliftingNews',
    'videos',
    'worldnews',
    'writingprompts'
]